language core;
extend with #natural-literals,#exceptions,#arithmetic-operators,#exception-type-declaration,#comparison-operators,#multiparameter-functions;

exception type = Bool

fn main(x : Nat) -> Bool {
    return try { 42 } catch { e => e }  // ошибка: try возвращает Nat, а функция Bool
}

//ERROR_UNEXPECTED_TYPE_FOR_EXPRESSION